<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>管理后台</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <link rel="stylesheet" href="/style/x_admin/css/font.css">
    <link rel="stylesheet" href="/style/x_admin/css/xadmin.css">
    <script src="/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/style/x_admin/js/xadmin.js"></script>
    <script type="text/javascript" src="/static/modules.js?v={{style_ver}}"></script>
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body ">
                    <blockquote class="layui-elem-quote">菜单节点</blockquote>
                </div>
                <div class="layui-card-header" style="margin-top:-13px;">
                    <a class="layui-btn" href="/backend/authority/menu/add"><i class="layui-icon"></i>添加菜单节点</a>
                </div>
                <div class="layui-card-body ">
                    <table class="layui-table layui-form">
                        <thead>
                        <tr>
                            <th width="90">ID</th>
                            <th width="50">图标</th>
                            <th>菜单名称</th>
                            <th width="200">规则路径</th>
                            <th width="90">排序</th>
                            <th width="80">状态</th>
                            <th width="110">操作</th>
                        </tr>
                        </thead>
                        <tbody class="x-cate">
                        {% if dataList %}
                        {% for key,item in dataList %}
                        <tr cate-id="{{item['id']}}" fid="{{item['parent_id']}}">
                            <td>{{item['id']}}</td>
                            <td>
                                {% if not is_empty(item['icon']) %}
                                <i class="iconfont left-nav-li">{{item['icon']}}</i>
                                {% endif %}
                            </td>
                            <td>{{item['title']}}</td>
                            <td>{{item['rule_path']}}</td>
                            <td>{{item['weigh']}}</td>
                            <td>
                                {{item['status']=='normal'?'<b style="color:green;">显示</b>':'<b
                                        style="color:red;">隐藏</b>'}}
                            </td>
                            <td class="td-manage">
                                <a href="javascript:" onclick="editFun({{item['id']}})">编辑</a>
                                <a href="javascript:" class="listForDel" data-id="{{item['id']}}">删除</a>
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="7">
                                暂无数据
                            </td>
                        </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="layui-card-body ">
                    <div class="page"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function editFun(id) {
        xadmin.open('编辑', '/backend/authority/menu/edit?id=' + id, '', '');
    }

    layui.use(['authority_menu'], function () {
        let m = layui.authority_menu;
        m.initList();
    });
</script>
</body>
</html>
