<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>管理后台</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <link rel="stylesheet" href="/style/x_admin/css/font.css">
    <link rel="stylesheet" href="/style/x_admin/css/xadmin.css">
    <script src="/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/style/x_admin/js/xadmin.js"></script>
    <script type="text/javascript" src="/static/modules.js?v={{style_ver}}"></script>
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body ">
                    <blockquote class="layui-elem-quote">编辑资料</blockquote>
                </div>
            </div>
        </div>
        <div class="layui-col-md12">
            <div class="layui-card">
                <form id="dataForm" class="layui-form" method="post" data-edit_id="{{adm.id}}">
                    <div class="layui-form-item">
                        <label class="layui-form-label">
                            <span class="x-red"></span>账号
                        </label>
                        <div class="layui-input-inline" style="width:200px;">
                            <div class="layui-form-mid layui-word-aux">{{adm.account}}</div>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="nickname" class="layui-form-label">
                            <span class="x-red"></span>昵称
                        </label>
                        <div class="layui-input-inline" style="width:200px;">
                            <input type="text" id="nickname" name="nickname"
                                   autocomplete="off" class="layui-input" maxlength="40" value="{{adm.nickname}}">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="realname" class="layui-form-label">
                            <span class="x-red"></span>真实姓名
                        </label>
                        <div class="layui-input-inline" style="width:200px;">
                            <input type="text" id="real_name" name="real_name"
                                   autocomplete="off" class="layui-input" maxlength="20" value="{{adm.real_name}}">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">头像</label>
                        <div class="layui-input-block">
                            <div class="layui-upload">
                                <button type="button" class="layui-btn" id="avatar_btn">上传图片</button>
                                <div class="layui-upload-list">
                                    <img class="layui-upload-img" id="avatar_prev"
                                         src="{{adm.avatar}}"
                                         style="width:120px;height:110px;">
                                    <p id="avatar_tip" style="color:red;"></p>
                                    <input type="hidden" id="avatar" name="avatar" value="{{adm.avatar}}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="title" class="layui-form-label">
                            <span class="x-red"></span>手机号
                        </label>
                        <div class="layui-input-inline" style="width:200px;">
                            <input type="text" id="mobile" name="mobile" required=""
                                   autocomplete="off" class="layui-input" maxlength="30" placeholder=""
                                   value="{{adm.mobile}}" lay-verify="phone">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="title" class="layui-form-label">
                            <span class="x-red"></span>邮箱
                        </label>
                        <div class="layui-input-inline" style="width:200px;">
                            <input type="text" id="mail" name="mail" required=""
                                   autocomplete="off" class="layui-input" maxlength="50" placeholder=""
                                   value="{{adm.mail}}" lay-verify="email">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label"></label>
                        <button id="submitBtn" class="layui-btn" lay-filter="submit" lay-submit="">
                            保 存
                        </button>
                    </div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    layui.use(
        ['jquery', 'form', 'layer', 'general_profile'],
        function () {
            let m = layui.general_profile;
            m.initEdit();
        }
    );
</script>
</body>
</html>
