<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>管理后台</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <link rel="stylesheet" href="/style/x_admin/css/font.css">
    <link rel="stylesheet" href="/style/x_admin/css/xadmin.css">
    <script src="/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/style/x_admin/js/xadmin.js"></script>
    <script type="text/javascript" src="/static/modules.js?v={{style_ver}}"></script>
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body ">
                    <blockquote class="layui-elem-quote">修改密码</blockquote>
                </div>
            </div>
        </div>
        <div class="layui-col-md12">
            <div class="layui-card">
                <form class="layui-form">
                    <div class="layui-form-item">
                        <label for="old_pwd" class="layui-form-label">
                            <span class="x-red"></span>旧密码
                        </label>
                        <div class="layui-input-inline">
                            <input type="password" id="old_pwd" name="old_pwd" required="" lay-verify="pass"
                                   autocomplete="off" class="layui-input" maxlength="22">
                        </div>
                        <div class="layui-form-mid layui-word-aux">
                            5到22个字符
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="new_pwd" class="layui-form-label">
                            <span class="x-red"></span>新密码
                        </label>
                        <div class="layui-input-inline">
                            <input type="password" id="new_pwd" name="new_pwd" required="" lay-verify="pass"
                                   autocomplete="off" class="layui-input" maxlength="22">
                        </div>
                        <div class="layui-form-mid layui-word-aux">
                            5到22个字符
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="cfm_new_pwd" class="layui-form-label">
                            <span class="x-red"></span>确认新密码
                        </label>
                        <div class="layui-input-inline">
                            <input type="password" id="cfm_new_pwd" name="cfm_new_pwd" required="" lay-verify="repass"
                                   autocomplete="off" class="layui-input" maxlength="22">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label"></label>
                        <button id="submitBtn" class="layui-btn" lay-filter="submit" lay-submit="">
                            修 改
                        </button>
                    </div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    layui.use(
        ['general_profile'],
        function () {
            let m = layui.general_profile;
            m.initChangePwd();
        }
    );
</script>
</body>
</html>
