<!doctype html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>后台登录</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link rel="stylesheet" href="/style/x_admin/css/font.css">
    <link rel="stylesheet" href="/style/x_admin/css/login.css">
    <link rel="stylesheet" href="/style/x_admin/css/xadmin.css">
    <script type="text/javascript" src="/lib/js/jquery-1.11.3.min.js"></script>
    <script src="/lib/layui/layui.js" charset="utf-8"></script>
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="login-bg">

<div class="login layui-anim layui-anim-up">
    <div class="message">管理登录</div>
    <div id="darkbannerwrap"></div>

    <form method="post" class="layui-form">
        <input name="username" placeholder="用户名" type="text" lay-verify="required"
               class="layui-input" value="" maxlength="22"/>
        <div style="width:100%;height:20px;"></div>
        <input name="password" lay-verify="required" placeholder="密码" type="password"
               class="layui-input" maxlength="22"/>
        <div style="width:100%;height:20px;"></div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <div class="layui-input-inline" style="width:110px;">
                    <input id="captcha" name="captcha" placeholder="验证码" type="text" lay-verify="required"
                           class="layui-input" maxlength="8"/>
                </div>
            </div>
            <div class="layui-inline">
                <div class="layui-input-inline" style="width:150px;">
                    <img id="captcha_img" src="/captcha" style="cursor: pointer;" title="点击刷新">
                </div>
            </div>
        </div>
        <div style="width:100%;height:15px;"></div>
        <input id="login_btn" value="登录" lay-submit lay-filter="login" style="width:100%;" type="submit">
        <div style="width:100%;height:20px;"></div>
    </form>
</div>
<script type="text/javascript" src="/lib/js/login.js" charset="utf-8"></script>
</body>
</html>
