<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>phadmin</title>
    <meta name="keywords" content="phadmin"/>
    <meta name="description" content="phadmin"/>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <script type="text/javascript" src="/lib/js/jquery-1.11.3.min.js"></script>
</head>
<body>
<div class="container">
    phadmin快速开发框架
</div>
<footer class="footer-area">

</footer>
<script type="text/javascript">
    //...
</script>
</body>
</html>
