<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>管理后台</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <link rel="stylesheet" href="/style/x_admin/css/font.css">
    <link rel="stylesheet" href="/style/x_admin/css/xadmin.css">
    <script src="/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/style/x_admin/js/xadmin.js"></script>
    <script type="text/javascript" src="/static/modules.js?v={{style_ver}}"></script>
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body ">
                    <blockquote class="layui-elem-quote">编辑系统配置</blockquote>
                </div>
            </div>
        </div>
        <div class="layui-col-md12">
            <div class="layui-card">
                <form id="dataForm" class="layui-form" method="post" data-edit_id="{{editData['id']}}">
                    <div class="layui-form-item">
                        <label for="cfg_key" class="layui-form-label">
                            <span class="x-red"></span>配置标识
                        </label>
                        <div class="layui-input-inline" style="width:40%;">
                            <input type="text" id="cfg_key" name="cfg_key" required=""
                                   autocomplete="off" class="layui-input" maxlength="57"
                                   placeholder="" value="{{editData['cfg_key']}}">
                        </div>

                    </div>
                    <div class="layui-form-item">
                        <label for="cfg_name" class="layui-form-label">
                            <span class="x-red"></span>配置名称
                        </label>
                        <div class="layui-input-inline" style="width:40%;">
                            <input type="text" id="cfg_name" name="cfg_name" required=""
                                   autocomplete="off" class="layui-input" maxlength="57"
                                   placeholder="" value="{{editData['cfg_name']}}">
                        </div>

                    </div>
                    <div class="layui-form-item">
                        <label for="cfg_value" class="layui-form-label">
                            <span class="x-red"></span>配置值
                        </label>
                        <div class="layui-input-inline" style="width:72%;">
                            <input type="text" id="cfg_value" name="cfg_value" required=""
                                   autocomplete="off" class="layui-input" placeholder=""
                                   value="{{editData['cfg_value']}}">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">状态</label>
                        <div class="layui-input-block">
                            <input type="radio" name="status" value="0" title="禁用" {% if('0'==editData['status']) %}checked="checked"{% endif %}>
                            <input type="radio" name="status" value="1" title="启用" {% if('1'==editData['status']) %}checked="checked"{% endif %}>
                        </div>

                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label"></label>
                        <button id="submitBtn" class="layui-btn" lay-filter="submit" lay-submit="">
                            保　　存
                        </button>
                    </div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    //var
    layui.use(
        ['general_config'],
        function () {
            let m = layui.general_config;
            m.initEdit();
        }
    );
</script>
</body>
</html>
