<!DOCTYPE html>
<html class="x-admin-sm">
<head>
    <meta charset="UTF-8">
    <title>管理后台</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <link rel="stylesheet" href="/style/x_admin/css/font.css">
    <link rel="stylesheet" href="/style/x_admin/css/xadmin.css">
    <script src="/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/style/x_admin/js/xadmin.js"></script>
    <script type="text/javascript" src="/static/modules.js?v={{style_ver}}"></script>
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body ">
                    <blockquote class="layui-elem-quote">添加角色</blockquote>
                </div>
            </div>
        </div>
        <div class="layui-col-md12">
            <div class="layui-card">
                <form id="dataForm" class="layui-form" method="post">
                    <div class="layui-form-item">
                        <label for="role_name" class="layui-form-label">
                            <span class="x-red"></span>角色名称
                        </label>
                        <div class="layui-input-inline" style="width:260px;">
                            <input type="text" id="role_name" name="role_name" required="required"
                                   autocomplete="off" class="layui-input" maxlength="30"
                                   lay-verify="role_name">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label for="intro" class="layui-form-label">
                            <span class="x-red"></span>描述或简介
                        </label>
                        <div class="layui-input-inline" style="width:560px;">
                            <input type="text" id="intro" name="intro" autocomplete="off"
                                   class="layui-input" maxlength="180" value="">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label"><span class="x-red"></span>分配权限</label>
                        <div class="layui-input-block" style="width:90%;">
                            <div id="LAY-auth-tree-index"></div>
                        </div>
                    </div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item">
                        <label class="layui-form-label"></label>
                        <button id="submitBtn" class="layui-btn" lay-filter="submit" lay-submit="">
                            保 存
                        </button>
                    </div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                    <div class="layui-form-item"></div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    layui.use(
        ['authority_role'],
        function () {
            let m = layui.authority_role;
            m.initAdd();
        }
    );
</script>
</body>
</html>
